version: '3.9'

services:
  app:
    build:
      context: . 
    ports:
      - "6001:6001" 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development 
